apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
namespace: default
images: #xTODO
  - name: backend
    newName: 194849407325.dkr.ecr.us-east-1.amazonaws.com/backend
    newTag: latest