name: Backend App
on:
  workflow_dispatch:
  pull_request:
    branches:
        - main
    paths:
      - 'starter/backend/**'
  
env:
  PYTHON_VERSION: '3.10'

jobs:
  lint:
    name: Running linter
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: starter/backend

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Install pipenv
      run: pip install pipenv

    - name: Install project dependencies
      run: pipenv install

    - name: Lint code
      run: pipenv run lint

  test:
    name: Running tests
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: starter/backend

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install project dependencies
      run: pipenv install

    - name: Run tests
      run: pipenv run test

  build:
    name: Build image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    needs:
      - lint
      - test 
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}

    - name: Install pipenv
      run: pip install pipenv

    - name: Install pipenv
      run: pipenv install

    - name: Build  image
      run: |
        docker build -t backend:latest .